### ISSUE TITLE
firewalla gold edition won't allow connection to home bridge

### ISSUE THREAD

**Issue by deniscooper** [mbierman/homebridge-installer#1]
Hi, not sure if you can help, running your script on firewall gold edition but I'm running into an issue with node, when I check the container logs I'm getting 

1: 0xcc7e17 node::Assert(node::AssertionInfo const&) [/opt/homebridge/bin/node]
 2: 0xd4818e node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [/opt/homebridge/bin/node]
 3: 0xd4826c node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [/opt/homebridge/bin/node]
 4: 0xc7bd07  [/opt/homebridge/bin/node]
 5: 0xc7d264 node::Start(int, char**) [/opt/homebridge/bin/node]
 6: 0x7fc410c96d90  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7fc410c96e40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xbd12ee _start [/opt/homebridge/bin/node]

this is a vanilla install. 

lsb_release -rs shows 18.04

the container shows as running, but looks like It is just in a restart loop - the config file doesn't get created

**Comment by mbierman** [comment]
Which Gold are you running? All my boxes are running the latest build which is build on 22.x. You may want to flash Firewalla to the latest version.

**Comment by deniscooper** [comment]
Flashing the firewall to 22 seems to have fixed the issue. Thanks.
